zuul:
   routes:
      events:
         path: /api/events/**
         sensitiveHeaders: null
         url: http://localhost:8089/manager/events
      auth:
         path: /api/auth/**
         url: http://localhost:8090/auth
      users:
         path: /api/users/**
         sensitiveHeaders: null
         url: http://localhost:8090/users
      analytics:
         path: /api/analytics/**
         sensitiveHeaders: null
         url: http://localhost:8095/analytics
eureka:
   client:
      enabled: false