zuul:
   routes:
      events:
         path: /events/**
         sensitiveHeaders: null
         url: http://localhost:8089/manager/events
      auth:
         path: /auth/**
         url: http://localhost:8090/auth
      users:
         path: /users/**
         sensitiveHeaders: null
         url: http://localhost:8090/users
      analytics:
         path: /analytics/**
         sensitiveHeaders: null
         url: http://localhost:8095/analytics
eureka:
   client:
      enabled: false